name: Run Tests with Allure Report and Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      driver:
        description: 'Browser driver to use (chrome or firefox)'
        required: true
        default: 'chrome'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome
      if: ${{ github.event.inputs.driver == 'chrome' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Firefox
      if: ${{ github.event.inputs.driver == 'firefox' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Run tests with Allure
      continue-on-error: true
      run: |
        pytest --driver=${{ github.event.inputs.driver }} --alluredir=allure-results

    - name: Install Allure CLI
      if: always()
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        allure --version

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
        force_orphan: true